import type { Artigo } from "@/lib/conteudo";

export const artigoTransicao: Artigo = {
  slug: "como-organizar-a-transicao-entre-sindicos",
  titulo: "Como organizar a transição entre síndicos sem perder informação",
  resumo:
    "A troca já foi decidida. Agora o desafio é operacional: entregar contratos, acessos, obras em curso e histórico financeiro sem deixar buracos na gestão. Um roteiro prático de transição.",
  categoria: "Gestão",
  data: "2024-07-08",
  ctaTipo: "check",
  relacionados: [
    "como-trocar-de-sindico-profissional",
    "como-contratar-um-sindico-profissional",
    "o-que-analisar-no-curriculo-de-um-sindico-profissional",
  ],
  keywords: ["transição entre síndicos", "passagem de gestão condomínio", "checklist troca de síndico"],
  conteudo: [
    { tipo: "p", texto: "Decidir a troca é a parte visível. A parte que realmente determina se o condomínio sai ganhando ou perdendo é a transição: o período em que a gestão anterior entrega e a nova gestão assume contratos, obrigações, acessos e histórico. Transições mal conduzidas geram retrabalho por meses — contratos que ninguém encontra, obras sem documentação, fornecedores cobrando serviços que não constam em lugar nenhum." },
    { tipo: "h2", texto: "Defina uma data de corte e um período de sobreposição" },
    { tipo: "p", texto: "A transição precisa de dois marcos claros: a data de corte contábil (até quando as obrigações são da gestão anterior) e o período de sobreposição, em que o síndico que sai ainda responde dúvidas do que entra. Quinze dias costumam ser suficientes em condomínios pequenos; em operações grandes, com obra em curso ou processos judiciais, trinta dias são mais realistas." },
    { tipo: "h2", texto: "Checklist financeiro" },
    { tipo: "lista", itens: [
      "Extratos bancários e conciliação até a data de corte",
      "Saldo de fundo de reserva e de fundos específicos, com destinação declarada",
      "Relação de inadimplentes com valores, fase de cobrança e escritório responsável",
      "Contas a pagar já comprometidas com vencimento após a troca",
      "Última prestação de contas aprovada e as pendentes de aprovação",
      "Situação de tributos, encargos trabalhistas e recolhimentos da equipe",
    ]},
    { tipo: "h2", texto: "Checklist de contratos e fornecedores" },
    { tipo: "lista", itens: [
      "Cópia de todos os contratos vigentes, com prazos, reajustes e cláusulas de rescisão",
      "Contatos operacionais de cada fornecedor, não apenas o comercial",
      "Histórico recente de problemas ou renegociações em andamento",
      "Apólices de seguro, coberturas e datas de renovação",
      "Contratos com vencimento nos próximos 90 dias, sinalizados como prioridade",
    ]},
    { tipo: "h2", texto: "Checklist de obras e manutenção" },
    { tipo: "p", texto: "Obras em andamento são o ponto mais frágil de qualquer transição. Sem cronograma, medições e ART/RRT organizados, o novo síndico assume um compromisso técnico que não consegue fiscalizar. Exija a pasta completa: projeto, contrato, cronograma físico-financeiro, medições pagas, laudos e comunicações formais com a empresa executora." },
    { tipo: "lista", itens: [
      "Plano de manutenção preventiva e histórico de execução",
      "Laudos obrigatórios e datas de vencimento (elevadores, SPDA, incêndio, gás)",
      "Garantias construtivas ainda vigentes e notificações já feitas à construtora",
    ]},
    { tipo: "h2", texto: "Checklist de acessos e sistemas" },
    { tipo: "lista", itens: [
      "Portal bancário, com troca imediata de senhas e procurações",
      "Sistema de gestão condominial e software contábil",
      "Sistemas de portaria, CFTV, controle de acesso e interfone",
      "E-mail institucional, canais de comunicação com moradores e redes do condomínio",
      "Chaves físicas, cartões e credenciais de áreas técnicas",
    ]},
    { tipo: "h2", texto: "Checklist jurídico e documental" },
    { tipo: "lista", itens: [
      "Processos judiciais e administrativos em curso, com escritório responsável",
      "Convenção, regimento interno e atas dos últimos anos",
      "Notificações e advertências aplicadas que ainda produzem efeito",
      "Documentação da equipe própria: contratos, exames, férias, banco de horas",
    ]},
    { tipo: "h2", texto: "Formalize a entrega em um termo assinado" },
    { tipo: "p", texto: "Todo item entregue deve constar em um termo de transição assinado pelas duas partes e pelo conselho. Esse documento cumpre duas funções: protege o síndico que sai de responsabilizações genéricas e protege o condomínio contra a perda de informação. Quando algo não é entregue, o termo registra a ausência — o que já é, por si só, um dado relevante." },
    { tipo: "h2", texto: "Comunique moradores no ritmo certo" },
    { tipo: "p", texto: "Comunique a troca depois de definidos os marcos da transição, não antes. O comunicado deve dizer quem assume, a partir de quando, quais canais mudam e o que permanece igual. Evite justificar a saída com críticas públicas à gestão anterior: além do risco jurídico, isso inaugura a nova gestão em clima de conflito." },
    { tipo: "h2", texto: "Os primeiros 30 dias da nova gestão" },
    { tipo: "lista", itens: [
      "Validar na prática o que foi recebido no termo de transição",
      "Visitar áreas técnicas e conferir o estado real da manutenção",
      "Reunir-se individualmente com os principais fornecedores",
      "Apresentar ao conselho um diagnóstico do que encontrou, sem promessas prematuras",
      "Definir prioridades dos primeiros 90 dias com o conselho, por escrito",
    ]},
    { tipo: "citacao", texto: "Uma transição bem documentada vale mais do que qualquer discurso de posse. O que não está registrado vira problema do próximo." },
    { tipo: "h2", texto: "Quando vale trazer um terceiro para a transição" },
    { tipo: "p", texto: "Em condomínios com obra relevante, passivo trabalhista ou histórico de desorganização, faz sentido envolver um terceiro — administradora, contador independente ou uma avaliação estruturada como o Q1S Check — para verificar o que está sendo entregue. Não é desconfiança: é o mesmo cuidado que se toma em qualquer troca de responsável por um patrimônio coletivo." },
  ],
};
