import type { Artigo } from "@/lib/conteudo";

export const artigoObras: Artigo = {
  slug: "como-escolher-um-sindico-para-condominio-com-obras",
  titulo: "Como escolher um síndico para condomínio com obras",
  resumo:
    "Retrofit de fachada, reforma estrutural ou grande manutenção mudam o perfil de síndico necessário. Veja o que avaliar antes de contratar.",
  categoria: "Obras",
  data: "2024-06-18",
  ctaTipo: "executive-search",
  relacionados: [
    "sindico-ideal-existe",
    "o-que-analisar-no-curriculo-de-um-sindico-profissional",
    "como-comparar-propostas-de-sindicos-profissionais",
  ],
  keywords: [
    "síndico para obras",
    "retrofit de fachada condomínio",
    "obra em condomínio",
    "gestão de obras condominiais",
  ],
  conteudo: [
    { tipo: "p", texto: "Poucas situações testam tanto uma gestão condominial quanto uma obra de grande porte. Retrofit de fachada, troca de prumadas, recuperação estrutural, impermeabilização de lajes e reforma de áreas comuns envolvem valores altos, prazos longos, convivência prejudicada e uma exposição contínua do síndico ao julgamento dos moradores." },
    { tipo: "p", texto: "Por isso, quando o condomínio tem obra prevista ou em andamento, o critério de escolha do síndico muda. A pergunta deixa de ser apenas quem administra bem o dia a dia e passa a ser quem já conduziu processos como este até o fim." },
    { tipo: "h2", texto: "Por que obra exige um repertório específico" },
    { tipo: "p", texto: "Gerir obra não é contratar um empreiteiro e acompanhar o andamento. É coordenar um processo técnico, financeiro, jurídico e político ao mesmo tempo, em que erros no início se tornam caros no meio e quase irreversíveis no fim." },
    { tipo: "lista", itens: [
      "Definição de escopo técnico com apoio de profissional habilitado, antes de qualquer cotação",
      "Concorrência estruturada, com propostas comparáveis sobre o mesmo escopo",
      "Análise de idoneidade e capacidade técnica das empresas concorrentes",
      "Contrato com cronograma físico-financeiro, garantias, retenções e critérios de medição",
      "Fiscalização independente da execução, separada da própria empresa executora",
      "Gestão do impacto sobre os moradores: ruído, poeira, acesso, estacionamento, prazos",
      "Prestação de contas periódica e transparente sobre desembolso e avanço real",
    ]},
    { tipo: "h2", texto: "O que avaliar no candidato" },
    { tipo: "h3", texto: "Histórico concreto de obras conduzidas" },
    { tipo: "p", texto: "Peça descrição de obras específicas: tipo de intervenção, porte do condomínio, duração prevista e duração real, valor aproximado, se houve aditivo e por quê. Um profissional experiente fala com naturalidade sobre atrasos e imprevistos, porque eles fazem parte da realidade de obra. Respostas genéricas sobre \"várias reformas\" indicam pouca vivência de responsabilidade direta." },
    { tipo: "h3", texto: "Compreensão do papel técnico de cada agente" },
    { tipo: "p", texto: "O síndico não é engenheiro, e não deveria tentar ser. O que se espera dele é a compreensão clara de quem faz o quê: quem elabora o laudo e o projeto, quem executa, quem fiscaliza, quem emite ART ou RRT, quem responde tecnicamente por cada etapa. Candidatos que dispensam assessoria técnica para economizar costumam gerar prejuízo maior adiante." },
    { tipo: "h3", texto: "Capacidade de conduzir a aprovação em assembleia" },
    { tipo: "p", texto: "Obra grande exige decisão coletiva sobre valores relevantes, muitas vezes com rateio extraordinário. O síndico precisa saber preparar material claro, apresentar alternativas com custos e consequências, responder a objeções sem confronto e conduzir a votação com segurança jurídica quanto a quórum e formalidades." },
    { tipo: "h3", texto: "Disciplina financeira durante a execução" },
    { tipo: "p", texto: "Obra é o momento em que o controle financeiro precisa ser mais rígido: pagamento vinculado a medição, retenção de garantia, acompanhamento de saldo do fundo de obras, controle de aditivos e registro de tudo. Vale perguntar como o candidato organiza esse controle e como reporta ao conselho." },
    { tipo: "h3", texto: "Comunicação durante o desgaste" },
    { tipo: "p", texto: "Meses de andaime, barulho e restrição de uso desgastam qualquer convivência. A diferença entre uma obra tolerada e uma obra revoltante quase sempre está na comunicação: cronograma divulgado, avisos antecipados de etapas críticas, canal para dúvidas e explicações honestas quando o prazo escorrega." },
    { tipo: "citacao", texto: "Em obra, o conselho não deve avaliar só se o síndico entende de construção. Deve avaliar se ele consegue conduzir pessoas durante um período longo de incômodo." },
    { tipo: "h2", texto: "Perguntas objetivas para a entrevista" },
    { tipo: "lista", itens: [
      "Qual foi a obra mais complexa que você conduziu e o que deu errado nela?",
      "Como você estrutura a concorrência entre empresas para garantir propostas comparáveis?",
      "Que profissional técnico você recomenda envolver e em que momento?",
      "Como você trata pedidos de aditivo durante a execução?",
      "Como você comunica um atraso de cronograma aos moradores?",
      "Como você garante que a obra seja recebida com verificação e garantia formalizada?",
    ]},
    { tipo: "h2", texto: "Sinais de alerta" },
    { tipo: "lista", itens: [
      "Promessa de prazo curto e valor baixo sem escopo técnico definido",
      "Indicação insistente de uma única empresa executora, sem concorrência",
      "Resistência a contratar fiscalização independente",
      "Desconhecimento de retenção de garantia e critérios de medição",
      "Histórico de obras iniciadas e não concluídas sob sua gestão",
    ]},
    { tipo: "h2", texto: "Quando faz sentido buscar um perfil dedicado" },
    { tipo: "p", texto: "Em condomínios com obra de grande porte, alta complexidade ou histórico anterior de tentativa frustrada, a busca por síndico costuma pedir um processo mais profundo do que a comparação de propostas recebidas. Nesses casos, faz sentido conduzir uma seleção dedicada, com definição prévia do perfil técnico necessário, busca ativa de profissionais com histórico específico em obras semelhantes, entrevistas estruturadas e checagem de referências focada justamente na condução de obras." },
    { tipo: "p", texto: "É esse o objetivo do Q1S Executive Search: tratar a contratação como um processo de recrutamento, e não como uma escolha entre os nomes que apareceram." },
  ],
};
