import type { Artigo } from "@/lib/conteudo";

export const artigoCurriculo: Artigo = {
  slug: "o-que-analisar-no-curriculo-de-um-sindico-profissional",
  titulo: "O que analisar no currículo de um síndico profissional",
  resumo:
    "Tempo de mercado diz pouco sozinho. Veja quais informações realmente importam no currículo de um síndico profissional e como interpretar cada uma delas.",
  categoria: "Contratação",
  data: "2024-06-04",
  ctaTipo: "check",
  relacionados: [
    "como-contratar-um-sindico-profissional",
    "perguntas-para-fazer-antes-de-contratar-um-sindico",
    "como-avaliar-referencias-de-um-sindico",
  ],
  keywords: [
    "currículo de síndico profissional",
    "experiência de síndico",
    "avaliar síndico profissional",
  ],
  conteudo: [
    { tipo: "p", texto: "O currículo de um síndico profissional costuma ser lido do jeito errado. O conselho olha o número de anos de atuação, a quantidade de condomínios administrados e conclui que quem tem mais tempo e mais volume é o candidato mais forte. Na prática, esses dois números isolados dizem muito pouco sobre a aderência do profissional ao seu condomínio específico. Um síndico com quinze anos de experiência em prédios de 40 unidades pode ter menos repertório para um condomínio clube de 500 unidades do que alguém com seis anos, mas dedicado justamente a esse porte." },
    { tipo: "p", texto: "Analisar um currículo bem é traduzir o que está escrito em evidências de repertório: quais situações esse profissional já enfrentou, em que contextos, com que grau de responsabilidade e com que resultado verificável." },
    { tipo: "h2", texto: "1. Porte e tipo dos condomínios atendidos" },
    { tipo: "p", texto: "Esta é a informação mais subestimada e uma das mais determinantes. A gestão de um edifício residencial de 60 unidades e a de um condomínio clube com áreas de lazer completas, equipe própria numerosa e orçamento mensal na casa das centenas de milhares de reais são atividades diferentes em rotina, em pressão e em competências exigidas." },
    { tipo: "lista", itens: [
      "Quantas unidades tinham, em média, os condomínios onde atuou?",
      "Eram residenciais verticais, horizontais, comerciais, mistos, loteamentos ou associações?",
      "Qual o padrão desses empreendimentos e o nível de exigência dos moradores?",
      "Havia equipe própria ou o serviço era terceirizado?",
    ]},
    { tipo: "h3", texto: "Como interpretar" },
    { tipo: "p", texto: "Experiência em porte igual ou superior ao do seu condomínio é um bom indicador. Experiência exclusivamente em portes muito menores não desqualifica o candidato, mas exige que ele demonstre, na entrevista, como pretende lidar com o salto de escala." },
    { tipo: "h2", texto: "2. Continuidade nos mandatos" },
    { tipo: "p", texto: "Mais revelador do que o total de condomínios atendidos é há quanto tempo o profissional permanece em cada um. Reconduções sucessivas em uma mesma assembleia indicam que moradores e conselho avaliaram positivamente o trabalho ao longo de anos — algo difícil de simular." },
    { tipo: "p", texto: "Trocas frequentes não são automaticamente um sinal negativo: contratos temporários para implantação, recuperação financeira ou condução de obra específica têm prazo naturalmente curto. O que importa é entender o motivo de cada saída. Um currículo com muitas passagens curtas e sem explicação clara é um ponto a investigar em profundidade nas referências." },
    { tipo: "h2", texto: "3. Situações críticas já enfrentadas" },
    { tipo: "p", texto: "Este é o núcleo do que chamamos de repertório. Gestão de condomínio é, em boa medida, gestão de exceções: a obra de fachada que atrasa, a inadimplência que dispara, o funcionário que precisa ser desligado, a assembleia tensa que precisa ser conduzida sem que a pauta descarrile." },
    { tipo: "lista", itens: [
      "Já conduziu obras estruturais, retrofit de fachada ou reformas de grande porte?",
      "Já assumiu condomínio em situação deficitária e reorganizou as contas?",
      "Já implantou condomínio novo, com toda a estrutura de contratos e rotinas a criar?",
      "Já reduziu inadimplência de forma sustentada e por quais mecanismos?",
      "Já geriu equipe própria com folha, escala, férias e passivo trabalhista?",
      "Já mediou conflitos graves entre moradores, conselho e administradora?",
    ]},
    { tipo: "p", texto: "Se o seu condomínio tem obra prevista, currículo sem histórico de obra é uma lacuna concreta — não um detalhe. O contrário também vale: exigir experiência em retrofit de quem vai gerir um prédio recém-entregue e sem intervenção prevista é criar um filtro inútil." },
    { tipo: "h2", texto: "4. Formação e atualização técnica" },
    { tipo: "p", texto: "Não existe formação obrigatória em lei para exercer a função de síndico profissional no Brasil. Isso torna a formação declarada um diferencial de contexto, não um requisito eliminatório. Cursos de gestão condominial, formação em administração, contabilidade, direito ou engenharia, e certificações de entidades do setor indicam investimento contínuo do profissional na própria qualificação." },
    { tipo: "p", texto: "Vale checar se a atualização é recente. Um curso feito há doze anos, sem nada depois, sinaliza menos comprometimento com atualização do que uma trilha de formação distribuída ao longo do tempo — especialmente em um setor cuja legislação, jurisprudência e tecnologia mudam com frequência." },
    { tipo: "h2", texto: "5. Estrutura de apoio declarada" },
    { tipo: "p", texto: "Síndico profissional que atua sozinho e síndico que trabalha apoiado por uma equipe entregam rotinas diferentes. Nenhum dos dois modelos é superior por natureza, mas eles precisam ser compatíveis com o que o seu condomínio demanda." },
    { tipo: "lista", itens: [
      "Trabalha sozinho, com auxiliares, ou dentro de uma empresa de gestão?",
      "Quem responde quando ele está em férias, doente ou em outro condomínio?",
      "Quantos condomínios atende simultaneamente hoje?",
      "Quem cuida da parte administrativa, jurídica e contábil no dia a dia?",
    ]},
    { tipo: "citacao", texto: "Um currículo bom não é o mais longo. É o que permite ao conselho prever, com segurança razoável, como aquele profissional vai se comportar nos problemas que o condomínio realmente tem." },
    { tipo: "h2", texto: "6. Coerência entre o que é declarado e o que é verificável" },
    { tipo: "p", texto: "Toda informação relevante do currículo deve ser verificável de alguma forma: nomes de condomínios (quando houver autorização para divulgação), períodos, contatos de conselheiros dispostos a dar referência, registros públicos de obras conduzidas. Informações genéricas e sem lastro — \"ampla experiência\", \"vasto conhecimento\", \"resultados expressivos\" — não devem entrar na conta da avaliação." },
    { tipo: "p", texto: "Quando um candidato hesita em detalhar períodos, portes ou motivos de saída, esse é o ponto exato onde a checagem de referências precisa se concentrar." },
    { tipo: "h2", texto: "7. Sinais que merecem investigação adicional" },
    { tipo: "lista", itens: [
      "Lacunas temporais longas sem explicação no histórico de atuação",
      "Descrições de responsabilidade incompatíveis com o porte declarado dos condomínios",
      "Ausência total de contatos de referência disponíveis",
      "Discurso centrado apenas em corte de custos, sem menção a manutenção e conservação",
      "Divergência entre o que consta no currículo e o que aparece em fontes públicas",
    ]},
    { tipo: "h2", texto: "Como transformar a análise em decisão" },
    { tipo: "p", texto: "Monte uma tabela simples com as dimensões que o seu condomínio exige — porte, tipo, obra, financeiro, equipe, conflitos, governança — e marque, para cada candidato, se existe evidência concreta, evidência parcial ou nenhuma evidência. O resultado deixa de ser uma impressão subjetiva e passa a ser um mapa de aderência e de lacunas, muito mais útil para conduzir entrevistas e checar referências com foco." },
    { tipo: "p", texto: "É exatamente essa lógica que estrutura a análise do Q1S Check: partir do currículo declarado, confrontá-lo com histórico, referências e informações públicas pertinentes, e devolver ao condomínio mais informação para uma decisão mais segura." },
  ],
};
