import type { Artigo } from "@/lib/conteudo";

export const artigoExecutiveSearch: Artigo = {
  slug: "quando-contratar-executive-search-para-sindico",
  titulo: "Quando faz sentido contratar um Executive Search para encontrar um síndico",
  resumo:
    "Nem todo condomínio precisa de uma busca conduzida. Veja em quais cenários o processo dedicado de hunting, entrevistas e validação compensa — e quando uma busca direta na base resolve.",
  categoria: "Contratação",
  data: "2024-08-19",
  ctaTipo: "executive-search",
  relacionados: [
    "como-contratar-um-sindico-profissional",
    "sindico-ideal-existe",
    "como-avaliar-referencias-de-um-sindico",
  ],
  keywords: ["executive search síndico", "headhunter de síndico", "recrutamento de síndico profissional"],
  conteudo: [
    { tipo: "p", texto: "Executive Search é o processo em que alguém conduz a busca por você: mapeia profissionais, aborda quem não está procurando vaga, entrevista, valida histórico, checa referências e apresenta uma shortlist justificada. No mercado condominial isso ainda é recente — a maioria das trocas acontece por indicação de conhecido ou por anúncio informal em grupo. E é exatamente aí que moram os erros mais caros." },
    { tipo: "h2", texto: "A diferença entre buscar e ser buscado" },
    { tipo: "p", texto: "Quando o condomínio publica que procura síndico, ele alcança quem está disponível. Quando alguém conduz a busca, alcança também quem está bem empregado, com contratos ativos e resultado comprovado — perfil que raramente responde a anúncio. Essa diferença é pequena em condomínios simples e enorme em operações complexas, onde a oferta de profissionais realmente preparados é reduzida." },
    { tipo: "h2", texto: "Cenários em que o Executive Search compensa" },
    { tipo: "h3", texto: "1. Condomínio grande ou de alta complexidade" },
    { tipo: "p", texto: "Múltiplas torres, centenas de unidades, equipe própria numerosa, orçamento anual robusto. O universo de profissionais com repertório real nessa escala é pequeno, e a maior parte não está circulando publicamente." },
    { tipo: "h3", texto: "2. Obra estrutural em andamento ou iminente" },
    { tipo: "p", texto: "Retrofit de fachada, troca de prumadas, reforma de garagem. Aqui o erro de contratação tem preço direto: cronograma estourado, medição mal fiscalizada, aditivos aceitos sem análise. Vale investir em um processo que verifique obra por obra o que o candidato realmente conduziu." },
    { tipo: "h3", texto: "3. Recuperação financeira ou crise instalada" },
    { tipo: "p", texto: "Caixa negativo, inadimplência alta, fornecedores suspendendo serviço. O condomínio não tem uma segunda tentativa: contratar errado agrava a crise. A busca conduzida permite priorizar candidatos com histórico específico de recuperação, e não apenas boa administração em cenário estável." },
    { tipo: "h3", texto: "4. Sucessão delicada ou conselho dividido" },
    { tipo: "p", texto: "Quando o conselho não tem consenso, um processo estruturado com critérios definidos antes das entrevistas reduz a disputa política. A decisão passa a se apoiar em evidências comparáveis, não em preferência pessoal por um nome." },
    { tipo: "h3", texto: "5. Depois de duas trocas seguidas malsucedidas" },
    { tipo: "p", texto: "Repetição de fracasso quase nunca é azar. Costuma indicar que o perfil buscado não corresponde ao que o condomínio realmente exige — e é justamente isso que um diagnóstico bem feito, antes da busca, corrige." },
    { tipo: "h2", texto: "Quando a busca direta já resolve" },
    { tipo: "lista", itens: [
      "Condomínio pequeno ou médio, com operação estável e sem obra relevante",
      "Conselho alinhado sobre o que procura e com critérios claros",
      "Necessidade bem definida e comum, com oferta ampla de profissionais na região",
      "Prazo confortável para entrevistar e comparar propostas por conta própria",
    ]},
    { tipo: "p", texto: "Nesses casos, filtrar por cidade, região e especialidade em uma base de profissionais e conduzir três a cinco entrevistas costuma ser suficiente. Contratar uma busca dedicada aqui adiciona custo sem adicionar informação." },
    { tipo: "h2", texto: "O que um processo conduzido entrega" },
    { tipo: "lista", itens: [
      "Diagnóstico do condomínio antes de qualquer nome ser considerado",
      "Definição do perfil necessário, com critérios explícitos e acordados com o conselho",
      "Mapeamento ativo de profissionais, inclusive fora do mercado aberto",
      "Triagem e entrevistas estruturadas com o mesmo roteiro para todos",
      "Validação de histórico e verificação do que foi declarado",
      "Checagem de referências junto a condomínios anteriores",
      "Shortlist com poucos nomes e justificativa objetiva para cada um",
    ]},
    { tipo: "h2", texto: "O que ele não entrega" },
    { tipo: "p", texto: "Nenhum processo elimina risco. Executive Search reduz a chance de erro grosseiro, aumenta a qualidade do repertório apresentado e dá ao conselho uma decisão comparável e documentada. Não garante que a relação vá funcionar por cinco anos, nem substitui o acompanhamento do conselho depois da contratação. Quem promete garantia total está vendendo outra coisa." },
    { tipo: "citacao", texto: "O custo de uma busca conduzida é conhecido e único. O custo de uma contratação errada em condomínio grande costuma aparecer parcelado, por vários anos." },
    { tipo: "h2", texto: "Como decidir" },
    { tipo: "p", texto: "Pergunte ao conselho três coisas: o quanto uma escolha errada custaria financeiramente nos próximos doze meses; se o grupo tem tempo e método para conduzir entrevistas e checagens; e se o perfil necessário já está claro. Se as respostas apontam para alto impacto, pouco tempo e perfil indefinido, a busca conduzida é o caminho mais racional. Se apontam para o oposto, comece pelo diagnóstico e pela busca direta." },
  ],
};
